<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <TargetFramework>net4.8</TargetFramework>
    <Configurations>Debug;Develop;Release</Configurations>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x64' ">
    <PlatformTarget>x64</PlatformTarget>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <Optimize>false</Optimize>
    <OutputPath>..\..\..\generated\outputs\Debug\</OutputPath>
    <IntermediateOutputPath>..\..\..\generated\obj\Script\Debug\</IntermediateOutputPath>
    <DefineConstants></DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Develop|x64' ">
    <PlatformTarget>x64</PlatformTarget>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <Optimize>false</Optimize>
    <OutputPath>..\..\..\generated\outputs\Develop\</OutputPath>
    <IntermediateOutputPath>..\..\..\generated\obj\Script\Develop\</IntermediateOutputPath>
    <DefineConstants></DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x64' ">
    <PlatformTarget>x64</PlatformTarget>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <Optimize>true</Optimize>
    <OutputPath>..\..\..\generated\outputs\Release\</OutputPath>
    <IntermediateOutputPath>..\..\..\generated\obj\Script\Release\</IntermediateOutputPath>
    <DefineConstants></DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x64' ">
  </ItemGroup>
  <ItemGroup Condition=" '$(Configuration)|$(Platform)' == 'Develop|x64' ">
  </ItemGroup>
  <ItemGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x64' ">
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Mathematic\Vector2.cs" />
    <Compile Include="Mathematic\Vector3.cs" />
    <Compile Include="Mathematic\Vector4.cs" />
    <Compile Include="Test.cs" />
    <Compile Include="Transform\QuaternionTransform.cs" />
    <Compile Include="obj\Develop\net4.8\.NETFramework,Version=v4.8.AssemblyAttributes.cs" />
    <Compile Include="obj\Develop\net4.8\Script.AssemblyInfo.cs" />
  </ItemGroup>
</Project>